[package]
name = "snm_yarn"
version = "0.1.0"
edition = "2021"

[dependencies]
snm_core = { path = "../snm_core" }
snm_npm = { path = "../snm_npm" }
dialoguer = "0.11.0"
semver = "1.0.21"
async-trait = "0.1.79"
sha1 = "0.10.0"
openssl = { version = "0.10", features = ["vendored"] }