[workspace]
members = [
    "crates/cli",
    "crates/snm_node",
    "crates/snm_core",
    "crates/snm_package_manager",
    "crates/snm_read_npmrc"
]
resolver = "2"

[profile.release]
lto = true
strip = "none"
opt-level = "s"
codegen-units = 1
debug = 2
