[workspace]
members = [
    "crates/cli",
    "crates/snm_node",
    "crates/snm_core",
    "crates/snm_npm",
    "crates/snm_pnpm",
]
resolver = "2"

[profile.release]
lto = true
strip = "symbols"
opt-level = "s"
codegen-units = 1