[workspace]
members = [
    "crates/cli",
    "crates/snm_node",
    "crates/snm_core",
    "crates/snm_package_manager"
, "crates/snm_package_json", "crates/snm_npmrc", "crates/snm_current_dir"]
resolver = "2"

[profile.release]
lto = true
strip = "none"
opt-level = "s"
codegen-units = 1
debug = 2
