[package]
name = "snm_pnpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snm_package_manager = { path = "../snm_package_manager" }
snm_core = { path = "../snm_core" }
async-trait = "0.1.79"
