[package]
name = "snm_npm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snm_core = { path = "../snm_core" }
crossterm = "0.27.0"
dialoguer = "0.11.0"
async-trait = "0.1.79"