name: canary-ubuntu
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main 
jobs:
  build-ubuntu-arm:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ env.TARGET }}
      - name: Build binary
        run: |
          sudo apt-get install musl-tools
          cargo build --verbose --release --target ${{ env.TARGET }}
        env:
          RUST_BACKTRACE: full
      - name: Strip binary (linux and macos)
        run:  |
          for file in snm node npm npx pnpm pnpx yarn; do
            strip "target/${{ env.TARGET }}/release/$file"
          done
      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md target/${{ env.TARGET }}/release/{node,npm,npx,pnpm,pnpx,yarn,snm} archive/
          tar -czf ${{ env.TARGET }}.tar.gz -C archive  LICENSE README.md node npm npx pnpm pnpx yarn snm
          ls -l
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}.tar.gz
          path: ${{ env.TARGET }}.tar.gz

   
  