name: canary-mac-arm
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main 
jobs:
  build-canary-mac-arm:
    runs-on: macos-latest
    env:
      TARGET: aarch64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ env.TARGET }}
      - name: Build binary
        run: |
          cargo build --verbose --release --target ${{ env.TARGET }}
        env:
          RUST_BACKTRACE: full
      - name: Strip binary (linux and macos)
        run:  |
          for file in snm node npm pnpm yarn; do
            strip "target/${{ env.TARGET }}/release/$file"
          done
      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md target/${{ env.TARGET }}/release/{node,npm,pnpm,yarn,snm} archive/
          tar -czf ${{ env.TARGET }}.tar.gz -C archive LICENSE README.md node npm pnpm yarn snm
          ls -l
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}.tar.gz
          path: ${{ env.TARGET }}.tar.gz

   
  